# Generated by Django 2.2.5 on 2019-10-27 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(max_length=450)),
                ('paper_title', models.CharField(max_length=4000)),
                ('paper_link', models.CharField(max_length=3000)),
                ('page_comments', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PaperCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=20)),
                ('paper_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thoth_data_collector.PaperItem')),
            ],
        ),
        migrations.CreateModel(
            name='PaperAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('author_home_page', models.CharField(max_length=4000)),
                ('author_email_addr', models.CharField(max_length=200)),
                ('paper_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thoth_data_collector.PaperItem')),
            ],
        ),
    ]
