# Generated by Django 2.2.5 on 2019-11-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_data_collector', '0002_papercategory_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperitem',
            name='is_recommanded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paperitem',
            name='recommand_reason',
            field=models.TextField(default=''),
        ),
    ]
