# Generated by Django 2.2.5 on 2019-11-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_data_collector', '0003_auto_20191102_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperitem',
            name='recommand_by',
            field=models.CharField(default='', max_length=200),
        ),
    ]
