# Generated by Django 2.2.5 on 2019-11-02 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_data_collector', '0004_paperitem_recommand_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperitem',
            name='created_by',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='paperitem',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 13, 3, 5, 624438)),
        ),
        migrations.AddField(
            model_name='paperitem',
            name='update_by',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='paperitem',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 13, 3, 5, 624479)),
        ),
    ]
