# Generated by Django 2.2.5 on 2019-11-05 11:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_data_collector', '0007_auto_20191105_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueinfo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 11, 30, 17, 147436)),
        ),
        migrations.AlterField(
            model_name='issueinfo',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 11, 30, 17, 147394)),
        ),
        migrations.AlterField(
            model_name='issueinfo',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 11, 30, 17, 147462)),
        ),
        migrations.AlterField(
            model_name='paperitem',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 11, 30, 17, 147978)),
        ),
        migrations.AlterField(
            model_name='paperitem',
            name='issue_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='thoth_data_collector.IssueInfo'),
        ),
        migrations.AlterField(
            model_name='paperitem',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 11, 30, 17, 148005)),
        ),
    ]
