# Generated by Django 2.2.5 on 2019-11-05 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_data_collector', '0009_auto_20191105_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueinfo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 11, 32, 16, 609807)),
        ),
        migrations.AlterField(
            model_name='issueinfo',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 11, 32, 16, 609766)),
        ),
        migrations.AlterField(
            model_name='issueinfo',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 11, 32, 16, 609831)),
        ),
        migrations.AlterField(
            model_name='paperitem',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 11, 32, 16, 610389)),
        ),
        migrations.AlterField(
            model_name='paperitem',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 11, 32, 16, 610422)),
        ),
    ]
