# Generated by Django 2.2.7 on 2019-11-07 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_data_collector', '0008_auto_20191105_0701'),
        ('thoth_data_collector', '0010_auto_20191105_1132'),
    ]

    operations = [
    ]
