# Generated by Django 2.1.7 on 2019-11-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_data_collector', '0012_auto_20191107_0404'),
        ('thoth_data_collector', '0011_auto_20191107_1502'),
    ]

    operations = [
    ]
