# Generated by Django 2.2.5 on 2019-11-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_data_collector', '0012_auto_20191107_0404'),
        ('thoth_data_collector', '0011_auto_20191107_1502'),
    ]

    operations = [
    ]
