# Generated by Django 2.1.7 on 2019-11-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_data_collector', '0013_merge_20191117_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueinfo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='issueinfo',
            name='issue_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='issueinfo',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paperitem',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paperitem',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
