# Generated by Django 2.2.7 on 2019-12-03 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_data_collector', '0014_auto_20191117_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperitem',
            name='last_view_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 10, 59, 3, 85718)),
        ),
        migrations.AddField(
            model_name='paperitem',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paperitem',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
