# Generated by Django 2.1.7 on 2019-11-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_data_collector', '0013_merge_20191114_1222'),
        ('thoth_data_collector', '0014_auto_20191117_1432'),
    ]

    operations = [
    ]
