# Generated by Django 2.2.7 on 2019-12-03 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_data_collector', '0016_auto_20191203_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperitem',
            name='last_view_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
