# Generated by Django 2.2.7 on 2019-12-08 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_data_collector', '0017_auto_20191203_1100'),
        ('thoth_data_collector', '0015_merge_20191118_1330'),
    ]

    operations = [
    ]
