# Generated by Django 2.2.7 on 2019-12-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoth_data_collector', '0018_merge_20191208_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperitem',
            name='code_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
